version: "3.8"

services:

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    build: .
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command: >
      mlflow server 
      --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow_db 
      --default-artifact-root /app/mlruns 
      --host 0.0.0.0
    volumes:
      - ./mlruns:/app/mlruns

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin_config_local.py:/pgadmin4/config_local.py

volumes:
  postgres_data:
  pgadmin_data: